name: Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: [docker, light]
    container:
      image: catthehacker/ubuntu:act-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Enable auto-merge
        env:
          GIT_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR number, skipping"
            exit 0
          fi

          # Enable auto-merge via API
          curl -s -X POST \
            -H "Authorization: token ${GIT_TOKEN}" \
            -H "Content-Type: application/json" \
            "https://git.customable.host/api/v1/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge" \
            -d '{"Do":"merge","MergeAutoMerge":true}' || true

          echo "Auto-merge enabled for PR #${PR_NUMBER}"
