name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Check if we should skip CI (e.g., release commits)
  check:
    runs-on: [docker, light]
    container:
      image: catthehacker/ubuntu:act-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Check commit message
        id: check
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ ^chore\(release\): ]]; then
            echo "Skipping CI for release commit"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.skip != 'true'
    runs-on: [docker, light]
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Type check
        run: bun run typecheck
        continue-on-error: true

  validate-plugin:
    runs-on: [docker, light]
    container:
      image: catthehacker/ubuntu:act-latest
    needs: [check, build]
    if: needs.check.outputs.skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate plugin structure
        run: |
          # Check required files exist
          test -f plugin/.claude-plugin/plugin.json
          test -d plugin/hooks
          test -d plugin/scripts
          echo "Plugin structure validated"
