name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Separate concurrency group from release workflow
# Don't cancel - let CI finish even if new commits come in
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # Check if we should skip CI (e.g., release commits)
  check:
    runs-on: [docker, light]
    container:
      image: catthehacker/ubuntu:act-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Check commit message
        id: check
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ ^chore\(release\): ]]; then
            echo "Skipping CI for release commit"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.skip != 'true'
    runs-on: [docker, light]
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Type check
        run: pnpm run typecheck
        continue-on-error: true

  validate-plugin:
    runs-on: [docker, light]
    container:
      image: catthehacker/ubuntu:act-latest
    needs: [check, build]
    if: needs.check.outputs.skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Build plugin
        run: node scripts/build-plugin.mjs

      - name: Validate plugin structure
        run: |
          # Check required files exist
          test -f plugin/.claude-plugin/plugin.json
          test -d plugin/hooks
          test -f plugin/scripts/mcp-server.cjs
          test -f plugin/scripts/worker-service.cjs
          test -f plugin/scripts/smart-install.js
          echo "Plugin structure validated"
