/**
 * CLAUDE.md Handler
 *
 * Generates CLAUDE.md content for projects using AI.
 */

import { createLogger } from '@claude-mem/shared';
import type { ClaudeMdTaskPayload, ClaudeMdTask } from '@claude-mem/types';
import type { Agent } from '../agents/types.js';
import { CLAUDEMD_SYSTEM_PROMPT, buildClaudeMdPrompt } from './prompts.js';

const logger = createLogger('claudemd-handler');

/**
 * Observation data for CLAUDE.md generation
 */
export interface ObservationData {
  id: number;
  title: string;
  text: string;
  type: string;
  createdAt: number;
  tokens?: number;
}

/**
 * Summary data for CLAUDE.md generation
 */
export interface SummaryData {
  request?: string;
  investigated?: string;
  learned?: string;
  completed?: string;
  nextSteps?: string;
  createdAt: number;
}

/**
 * Handle a CLAUDE.md generation task
 */
export async function handleClaudeMdTask(
  agent: Agent,
  payload: ClaudeMdTaskPayload,
  observations: ObservationData[],
  summaries: SummaryData[]
): Promise<ClaudeMdTask['result']> {
  logger.debug(
    `Generating CLAUDE.md for ${payload.project} with ${observations.length} observations`
  );

  if (observations.length === 0) {
    // Return minimal CLAUDE.md content
    const content = `<claude-mem-context>
# Recent Activity

<!-- This section is auto-generated by claude-mem. Edit content outside the tags. -->

*No recent activity recorded for this project.*
</claude-mem-context>`;

    return {
      content,
      tokens: 0,
    };
  }

  // Build the prompt
  const userPrompt = buildClaudeMdPrompt(observations, summaries, payload.project);

  // Query the agent
  const response = await agent.query({
    system: CLAUDEMD_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
    maxTokens: 2048,
    temperature: 0.3,
  });

  // Extract content between <claude-mem-context> tags
  const content = extractClaudeMdContent(response.content);

  if (!content) {
    logger.warn('No claude-mem-context tags found in response, using raw content');
    // Wrap raw content in tags
    const wrapped = `<claude-mem-context>\n${response.content}\n</claude-mem-context>`;
    return {
      content: wrapped,
      tokens: response.inputTokens + response.outputTokens,
    };
  }

  return {
    content,
    tokens: response.inputTokens + response.outputTokens,
  };
}

/**
 * Extract content including the <claude-mem-context> tags
 */
function extractClaudeMdContent(text: string): string | null {
  const startTag = '<claude-mem-context>';
  const endTag = '</claude-mem-context>';

  const startIdx = text.indexOf(startTag);
  const endIdx = text.indexOf(endTag);

  if (startIdx === -1 || endIdx === -1) {
    return null;
  }

  // Include the tags themselves
  return text.slice(startIdx, endIdx + endTag.length);
}
